apiVersion: v1
kind: Secret
metadata:
  name: <<SECRET_CM_NAME>>
  namespace: <<NAMESPACE>>
type: Opaque
data:
  GATEWAY_DB_PASSWORD: "<<GATEWAY_DB_PASSWORD_ENCODED>>"
  MANAGER_DB_PASSWORD: "<<MANAGER_DB_PASSWORD_ENCODED>>"
  IDENTITY_DB_PASSWORD: "<<IDENTITY_DB_PASSWORD_ENCODED>>"
  WEB_DB_PASSWORD: "<<WEB_DB_PASSWORD_ENCODED>>"
  OPENJIUWEN_SERVICE_DB_PASSWORD: "<<RUNTIME_DB_PASSWORD_ENCODED>>"
  REDIS_PASSWORD: "<<REDIS_PASSWORD_ENCODED>>"
  OBS_SECRET_KEY: "<<OBS_SECRET_KEY_ENCODED>>"
  API_KEY: "<<API_KEY_ENCODED>>"
