# 1. Headless Service：给 StatefulSet 提供稳定 DNS 域名
apiVersion: v1
kind: Service
metadata:
  name: <<POSTGRESQL_NAME>>-headless
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: <<POSTGRESQL_NAME>>

---
# 2. NodePort Service：供外部工具连接 PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: <<POSTGRESQL_NAME>>-nodeport
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: <<POSTGRESQL_NODE_PORT>>
  selector:
    app: <<POSTGRESQL_NAME>>

---
# 3. StatefulSet：PostgreSQL 有状态应用
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: <<POSTGRESQL_NAME>>
spec:
  serviceName: <<POSTGRESQL_NAME>>-headless
  replicas: 1
  selector:
    matchLabels:
      app: <<POSTGRESQL_NAME>>
  template:
    metadata:
      labels:
        app: <<POSTGRESQL_NAME>>
    spec:
      containers:
        - name: <<POSTGRESQL_NAME>>
          image: <<POSTGRESQL_IMAGE>>
          args:
            - -c
            - max_connections=<<POSTGRESQL_MAX_CONNECTION>>
          env:
            - name: POSTGRES_PASSWORD
              value: "<<POSTGRESQL_PASSWORD>>"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "scram-sha-256"
            - name: TZ
              value: "<<TIMEZONE>>"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
              name: <<POSTGRESQL_NAME>>
          volumeMounts:
            - name: <<POSTGRESQL_NAME>>-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
      volumes:
        - name: <<POSTGRESQL_NAME>>-data
          persistentVolumeClaim:
            claimName: <<POSTGRESQL_NAME>>-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: <<POSTGRESQL_NAME>>-pv
  labels:
    app: <<POSTGRESQL_NAME>>
spec:
  capacity:
    storage: <<POSTGRESQL_STORAGE_SIZE>>
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: <<NFS_SERVER_ADDR>>
    path: <<NFS_SHARE_PATH>>/<<POSTGRESQL_NAME>>
    readOnly: false
  mountOptions:
    - nfsvers=4
    - soft        # 改成 soft！防止节点卡死
    - timeo=600   # 超时时间：60秒
    - retrans=2   # 重试2次
    - noatime

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <<POSTGRESQL_NAME>>-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: <<POSTGRESQL_STORAGE_SIZE>>
  storageClassName: ""
  selector:
    matchLabels:
      app: <<POSTGRESQL_NAME>>
