//go:build cgo

package store

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/mattn/go-sqlite3"

	"credential_router/internal/platform"
)

// Credential represents a row in the credentials table.
type Credential struct {
	ID           int64
	UserID       string
	APIBase      string
	KeyTag       string
	ProxyKey     string
	APIKeyCipher []byte
	AuthType     string
	RowVersion   int64
	KekVersion   int64
	DekVersion   int64
	CreatedAt    int64
	UpdatedAt    int64
}

// GenerateProxyKey returns a fresh, collision-resistant proxy lookup key:
// the literal prefix "cr_pk_" followed by 32 bytes of crypto/rand entropy
// encoded as unpadded base64url (43 chars). Uniqueness is enforced by the
// UNIQUE index idx_credentials_proxy_key; a collision (probability ~2^-256)
// is surfaced as platform.ErrConflict on the proxy_key column, which callers
// can detect with IsUniquenessConstraintFor and retry with a fresh key.
func GenerateProxyKey() string {
	var buf [32]byte
	if _, err := rand.Read(buf[:]); err != nil {
		// crypto/rand.Read is documented as never failing on supported
		// platforms; if it does, the process cannot mint safe keys.
		panic(fmt.Sprintf("store: GenerateProxyKey: crypto/rand failed: %v", err))
	}
	return "cr_pk_" + base64.RawURLEncoding.EncodeToString(buf[:])
}

// InsertCredential inserts a new credential. row_version defaults to 1.
// If c.ProxyKey is empty a fresh one is generated by GenerateProxyKey before
// the INSERT, so c.ProxyKey is always populated on return.
// Returns platform.ErrConflict on UNIQUE (user_id, api_base, key_tag) or
// UNIQUE (proxy_key) violation.
func (s *Store) InsertCredential(ctx context.Context, c *Credential) error {
	if c == nil {
		return fmt.Errorf("store: nil credential")
	}
	now := time.Now().Unix()
	c.CreatedAt = now
	c.UpdatedAt = now
	c.RowVersion = 1
	if c.KekVersion == 0 {
		c.KekVersion = 1
	}
	if c.DekVersion == 0 {
		c.DekVersion = 1
	}
	if c.ProxyKey == "" {
		c.ProxyKey = GenerateProxyKey()
	}
	res, err := s.adminDB.ExecContext(ctx,
		`INSERT INTO credentials
			(user_id, api_base, key_tag, proxy_key, api_key_cipher, auth_type,
			 row_version, kek_version, dek_version, created_at, updated_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		c.UserID, c.APIBase, c.KeyTag, c.ProxyKey, c.APIKeyCipher, c.AuthType,
		c.RowVersion, c.KekVersion, c.DekVersion, c.CreatedAt, c.UpdatedAt,
	)
	if err != nil {
		if IsUniquenessConstraintFor(err, "proxy_key") {
			// Collision on the generated key: transient and self-healing —
			// callers may retry (InsertCredential regenerates when ProxyKey
			// is empty). Still reported as a conflict, not a hard error.
			return fmt.Errorf("%w: proxy_key collision", platform.ErrConflict)
		}
		if isUniquenessConstraintError(err) {
			return fmt.Errorf("%w: user_id=%q api_base=%q key_tag=%q",
				platform.ErrConflict, c.UserID, c.APIBase, c.KeyTag)
		}
		return fmt.Errorf("store: insert credential: %w", err)
	}
	id, err := res.LastInsertId()
	if err != nil {
		return fmt.Errorf("store: last insert id: %w", err)
	}
	c.ID = id
	return nil
}

// GetCredentialByUserURLTag returns the credential matching the unique key.
// Returns platform.ErrNotFound if no row exists.
func (s *Store) GetCredentialByUserURLTag(ctx context.Context, userID, apiBase, keyTag string) (*Credential, error) {
	row := s.proxyDB.QueryRowContext(ctx,
		`SELECT id, user_id, api_base, key_tag, proxy_key, api_key_cipher, auth_type,
		        row_version, kek_version, dek_version, created_at, updated_at
		 FROM credentials
		 WHERE user_id = ? AND api_base = ? AND key_tag = ?`,
		userID, apiBase, keyTag,
	)
	c := &Credential{}
	err := row.Scan(
		&c.ID, &c.UserID, &c.APIBase, &c.KeyTag, &c.ProxyKey, &c.APIKeyCipher, &c.AuthType,
		&c.RowVersion, &c.KekVersion, &c.DekVersion, &c.CreatedAt, &c.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("%w: user_id=%q api_base=%q key_tag=%q",
				platform.ErrNotFound, userID, apiBase, keyTag)
		}
		return nil, fmt.Errorf("store: get credential: %w", err)
	}
	return c, nil
}

// GetCredentialByProxyKey returns the credential matching the proxy lookup
// key via the proxy read pool. Returns platform.ErrNotFound if no row exists.
func (s *Store) GetCredentialByProxyKey(ctx context.Context, proxyKey string) (*Credential, error) {
	row := s.proxyDB.QueryRowContext(ctx,
		`SELECT id, user_id, api_base, key_tag, proxy_key, api_key_cipher, auth_type,
		        row_version, kek_version, dek_version, created_at, updated_at
		 FROM credentials
		 WHERE proxy_key = ?`,
		proxyKey,
	)
	c := &Credential{}
	err := row.Scan(
		&c.ID, &c.UserID, &c.APIBase, &c.KeyTag, &c.ProxyKey, &c.APIKeyCipher, &c.AuthType,
		&c.RowVersion, &c.KekVersion, &c.DekVersion, &c.CreatedAt, &c.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("%w: proxy_key=%q", platform.ErrNotFound, proxyKey)
		}
		return nil, fmt.Errorf("store: get credential by proxy key: %w", err)
	}
	return c, nil
}

// GetCredentialByID returns a credential by its primary key. Uses proxyDB.
func (s *Store) GetCredentialByID(ctx context.Context, id int64) (*Credential, error) {
	row := s.proxyDB.QueryRowContext(ctx, `SELECT id, user_id, api_base, key_tag, proxy_key, api_key_cipher, auth_type, row_version, kek_version, dek_version, created_at, updated_at FROM credentials WHERE id = ?`, id)
	c := &Credential{}
	err := row.Scan(&c.ID, &c.UserID, &c.APIBase, &c.KeyTag, &c.ProxyKey, &c.APIKeyCipher, &c.AuthType, &c.RowVersion, &c.KekVersion, &c.DekVersion, &c.CreatedAt, &c.UpdatedAt)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("%w: id=%d", platform.ErrNotFound, id)
		}
		return nil, fmt.Errorf("store: get credential by id: %w", err)
	}
	return c, nil
}

// ListCredentials returns all credentials, ordered by id, with optional limit/offset.
func (s *Store) ListCredentials(ctx context.Context, limit, offset int) ([]*Credential, error) {
	if limit < 0 {
		return nil, fmt.Errorf("store: limit must be >= 0, got %d", limit)
	}
	if offset < 0 {
		return nil, fmt.Errorf("store: offset must be >= 0, got %d", offset)
	}
	q := `SELECT id, user_id, api_base, key_tag, proxy_key, api_key_cipher, auth_type,
	             row_version, kek_version, dek_version, created_at, updated_at
	      FROM credentials
	      ORDER BY id`
	var args []any
	if limit > 0 {
		q += ` LIMIT ?`
		args = append(args, limit)
		if offset > 0 {
			q += ` OFFSET ?`
			args = append(args, offset)
		}
	} else if offset > 0 {
		q += ` LIMIT -1 OFFSET ?`
		args = append(args, offset)
	}
	rows, err := s.proxyDB.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("store: list credentials: %w", err)
	}
	defer rows.Close()
	var out []*Credential
	for rows.Next() {
		c := &Credential{}
		if err := rows.Scan(
			&c.ID, &c.UserID, &c.APIBase, &c.KeyTag, &c.ProxyKey, &c.APIKeyCipher, &c.AuthType,
			&c.RowVersion, &c.KekVersion, &c.DekVersion, &c.CreatedAt, &c.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("store: scan credential: %w", err)
		}
		out = append(out, c)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: rows: %w", err)
	}
	return out, nil
}

// UpdateCredential updates api_key_cipher and/or auth_type with optimistic
// row_version lock. Caller signals "keep existing" per field by passing the
// zero value:
//
//	c.APIKeyCipher == nil → keep existing api_key_cipher
//	c.AuthType == ""     → keep existing auth_type
//
// c.KekVersion and c.DekVersion are ALWAYS overwritten (they reflect the
// encryption metadata of whatever cipher was just written; the caller MUST
// pass the snap's versions so Phase A can correctly identify rows that need
// re-encryption). row_version and updated_at are always managed here.
// On success it increments c.RowVersion and sets c.UpdatedAt and c.ID.
// Returns platform.ErrConflict if row_version doesn't match.
// Returns platform.ErrNotFound if id doesn't exist.
func (s *Store) UpdateCredential(ctx context.Context, id int64, c *Credential) error {
	if c == nil {
		return fmt.Errorf("store: nil credential")
	}
	if c.KekVersion == 0 {
		c.KekVersion = 1
	}
	if c.DekVersion == 0 {
		c.DekVersion = 1
	}
	now := time.Now().Unix()
	res, err := s.adminDB.ExecContext(ctx,
		`UPDATE credentials
		 SET api_key_cipher=COALESCE(?, api_key_cipher),
		     auth_type=COALESCE(NULLIF(?, ''), auth_type),
		     kek_version=?,
		     dek_version=?,
		     row_version=row_version+1,
		     updated_at=?
		 WHERE id=? AND row_version=?`,
		c.APIKeyCipher, c.AuthType, c.KekVersion, c.DekVersion, now, id, c.RowVersion,
	)
	if err != nil {
		return fmt.Errorf("store: update credential: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("store: rows affected: %w", err)
	}
	if n == 0 {
		// Distinguish: row missing or row_version mismatch
		var existing int64
		err := s.adminDB.QueryRowContext(ctx,
			`SELECT row_version FROM credentials WHERE id=?`, id,
		).Scan(&existing)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				return fmt.Errorf("%w: id=%d", platform.ErrNotFound, id)
			}
			return fmt.Errorf("store: lookup after failed update: %w", err)
		}
		return fmt.Errorf("%w: id=%d expected row_version=%d got=%d",
			platform.ErrConflict, id, c.RowVersion, existing)
	}
	c.RowVersion++
	c.UpdatedAt = now
	c.ID = id
	return nil
}

// DeleteCredential deletes a credential by id with optimistic row_version lock.
// Returns platform.ErrConflict if row_version doesn't match (row gone or version mismatch).
func (s *Store) DeleteCredential(ctx context.Context, id int64, expectedRowVersion int64) error {
	res, err := s.adminDB.ExecContext(ctx,
		`DELETE FROM credentials WHERE id=? AND row_version=?`,
		id, expectedRowVersion,
	)
	if err != nil {
		return fmt.Errorf("store: delete credential: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("store: rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("%w: id=%d", platform.ErrConflict, id)
	}
	return nil
}

// CountStragglersByDekVersion reports Phase A progress for the keystore status
// endpoint. Counts rows whose dek_version is below targetDek.
func (s *Store) CountStragglersByDekVersion(ctx context.Context, targetDek int64) (int64, error) {
	var n int64
	err := s.adminDB.QueryRowContext(ctx, "SELECT COUNT(*) FROM credentials WHERE dek_version < ?", targetDek).Scan(&n)
	if err != nil {
		return 0, fmt.Errorf("count stragglers: %w", err)
	}
	return n, nil
}

// isUniquenessConstraintError detects SQLite UNIQUE (2067) or PRIMARY KEY
// (1555) violations via the extended code; both are mappable to platform.ErrConflict.
func isUniquenessConstraintError(err error) bool {
	var sqliteErr sqlite3.Error
	if errors.As(err, &sqliteErr) {
		return sqliteErr.ExtendedCode == sqlite3.ErrConstraintUnique ||
			sqliteErr.ExtendedCode == sqlite3.ErrConstraintPrimaryKey
	}
	return false
}

// IsUniquenessConstraintFor reports whether err is a UNIQUE/PRIMARY KEY
// constraint violation affecting the named column. The credentials table now
// has two uniqueness dimensions — (user_id, api_base, key_tag) and proxy_key —
// and callers need to tell them apart: a proxy_key collision comes from the
// auto-generated key and is transient (retry with a fresh GenerateProxyKey),
// while a user_id/api_base/key_tag collision is a genuine duplicate.
func IsUniquenessConstraintFor(err error, column string) bool {
	if !isUniquenessConstraintError(err) {
		return false
	}
	var sqliteErr sqlite3.Error
	if errors.As(err, &sqliteErr) {
		return strings.Contains(sqliteErr.Error(), column)
	}
	return false
}
