# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.

"""Durable artifact store for EvidenceRail lifecycle receipts."""

from __future__ import annotations

import os
import threading
from pathlib import Path
from typing import Protocol

from .contracts import ContextDigest, RunManifest, ToolReceipt


class EvidenceRailStore(Protocol):
    """Persistence boundary used by :class:`EvidenceRail`."""

    def save_manifest(self, manifest: RunManifest) -> None: ...

    def append_context_digest(self, receipt: ContextDigest) -> None: ...

    def append_tool_receipt(self, receipt: ToolReceipt) -> None: ...


class FileEvidenceRailStore:
    """Filesystem store using atomic manifests and append-only JSONL receipts."""

    def __init__(self, artifact_root: str | Path) -> None:
        self.artifact_root = Path(artifact_root).expanduser().resolve()
        self._lock = threading.Lock()

    def save_manifest(self, manifest: RunManifest) -> None:
        run_dir = self._run_dir(manifest.run_id)
        payload = manifest.model_dump_json(indent=2) + "\n"
        with self._lock:
            run_dir.mkdir(parents=True, exist_ok=True)
            tmp = run_dir / ".run_manifest.json.tmp"
            tmp.write_text(payload, encoding="utf-8")
            os.replace(tmp, run_dir / "run_manifest.json")

    def append_context_digest(self, receipt: ContextDigest) -> None:
        self._append_jsonl(
            receipt.run_id,
            "context_digests.jsonl",
            receipt.model_dump_json(),
        )

    def append_tool_receipt(self, receipt: ToolReceipt) -> None:
        self._append_jsonl(
            receipt.run_id,
            "tool_receipts.jsonl",
            receipt.model_dump_json(),
        )

    def _append_jsonl(self, run_id: str, name: str, payload: str) -> None:
        run_dir = self._run_dir(run_id)
        with self._lock:
            run_dir.mkdir(parents=True, exist_ok=True)
            with (run_dir / name).open("a", encoding="utf-8") as stream:
                stream.write(payload)
                stream.write("\n")
                stream.flush()
                os.fsync(stream.fileno())

    def _run_dir(self, run_id: str) -> Path:
        # run_id is generated by the rail.  Keep this guard because callers may
        # provide a custom id factory when embedding the rail.
        if (
            not run_id
            or run_id in {".", ".."}
            or "/" in run_id
            or "\\" in run_id
            or Path(run_id).name != run_id
        ):
            raise ValueError("run_id must be one safe path component")
        return self.artifact_root / run_id


__all__ = ["EvidenceRailStore", "FileEvidenceRailStore"]
