"""Generated by scripts/build_config.py --sync; do not edit manually."""

from __future__ import annotations

PACKAGE_NAME = 'jiuwenswarm'
VERSION = '0.2.5.beta1'
DISPLAY_NAME = 'JiuwenSwarm'
EXECUTABLE_NAME = 'jiuwenswarm'
BUNDLE_IDENTIFIER = 'com.jiuwenswarm.desktop'
ERROR_LOG_NAME = 'jiuwenswarm_exe_error.log'
TUI_PACKAGE_NAME = 'jiuwenswarm-tui'
APP_FULL_NAME = 'JiuwenSwarm 0.2.5.beta1'
APP_BUNDLE_NAME = 'JiuwenSwarm.app'
EXECUTABLE_NAME_WINDOWS = 'jiuwenswarm.exe'
DIST_DIR_NAME = 'jiuwenswarm'
DMG_FILENAME = 'JiuwenSwarm-0.2.5.beta1-macos.dmg'
SETUP_BASE_NAME = 'JiuwenSwarm-0.2.5.beta1-windows'
SETUP_FILENAME = 'JiuwenSwarm-0.2.5.beta1-windows.exe'
