ARG BASE_IMAGE
ARG IMAGE_VERSION
FROM ${BASE_IMAGE}:${IMAGE_VERSION}

ARG NPM_REGISTRY=https://registry.npmmirror.com

WORKDIR /app/jiuwenswarm/jiuwenswarm/channels/web/frontend
ENV NPM_CONFIG_REGISTRY=${NPM_REGISTRY}
RUN npm install
RUN npm run build

WORKDIR /app/jiuwenswarm

EXPOSE 5173
CMD ["jiuwenswarm-start", "web"]