#!/usr/bin/env bash
set -euo >/dev/null 2>&1

# =============================================================================
# CORE DATA STRUCTURE
# =============================================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CUSTOM_ENV_FILE="${SCRIPT_DIR}/.env.custom"
TEMPLATE_DIR="${SCRIPT_DIR}/templates"
CONFIG_DIR="${SCRIPT_DIR}/conf"

# ===== Core project configuration (paths, ports, commands, OS info) =====
declare -A CONFIG=(
    ["NFS_TEMPLATE_FILE"]="${TEMPLATE_DIR}/nfs.template.yaml"
    ["NFS_FILE"]="${CONFIG_DIR}/nfs.yaml"

    ["NFS_SC_TEMPLATE_FILE"]="${TEMPLATE_DIR}/nfs-sc.template.yaml"
    ["NFS_SC_FILE"]="${CONFIG_DIR}/nfs-sc.yaml"

    ["MYSQL_TEMPLATE_FILE"]="${TEMPLATE_DIR}/mysql.template.yaml"
    ["MYSQL_FILE"]="${CONFIG_DIR}/mysql.yaml"

    ["POSTGRESQL_TEMPLATE_FILE"]="${TEMPLATE_DIR}/postgresql.template.yaml"
    ["POSTGRESQL_FILE"]="${CONFIG_DIR}/postgresql.yaml"

    ["RABBITMQ_TEMPLATE_FILE"]="${TEMPLATE_DIR}/rabbitmq.template.yaml"
    ["RABBITMQ_FILE"]="${CONFIG_DIR}/rabbitmq.yaml"

    ["REDIS_TEMPLATE_FILE"]="${TEMPLATE_DIR}/redis.template.yaml"
    ["REDIS_FILE"]="${CONFIG_DIR}/redis.yaml"

    ["MINIO_TEMPLATE_FILE"]="${TEMPLATE_DIR}/minio.template.yaml"
    ["MINIO_FILE"]="${CONFIG_DIR}/minio.yaml"

    ["LOG_TEMPLATE_FILE"]="${TEMPLATE_DIR}/log.template.yaml"
    ["LOG_FILE"]="${CONFIG_DIR}/log.yaml"

    ["JINA_TEMPLATE_FILE"]="${TEMPLATE_DIR}/jina.template.yaml"
    ["JINA_FILE"]="${CONFIG_DIR}/jina.yaml"
    ["PROXY_TEMPLATE_FILE"]="${TEMPLATE_DIR}/proxy.template.yaml"
    ["PROXY_FILE"]="${CONFIG_DIR}/proxy.yaml"

    ["SECRET_CM_TEMPLATE_FILE"]="${TEMPLATE_DIR}/configmap-secret.template.yaml"
    ["SECRET_CM_FILE"]="${CONFIG_DIR}/configmap-secret.yaml"

    ["GATEWAY_ENV_TEMPLATE_FILE"]="${TEMPLATE_DIR}/gateway.template.env"
    ["GATEWAY_ENV_FILE"]="${CONFIG_DIR}/gateway.env"
    ["GATEWAY_ENV_YAML_FILE"]="${CONFIG_DIR}/gateway-env.configmap.yaml"

    ["GATEWAY_TEMPLATE_FILE"]="${TEMPLATE_DIR}/gateway.template.yaml"
    ["GATEWAY_FILE"]="${CONFIG_DIR}/gateway.yaml"

    ["WEB_TEMPLATE_FILE"]="${TEMPLATE_DIR}/web.template.yaml"
    ["WEB_FILE"]="${CONFIG_DIR}/web.yaml"

    ["MANAGER_SERVER_TEMPLATE_FILE"]="${TEMPLATE_DIR}/manager-server.template.yaml"
    ["MANAGER_SERVER_FILE"]="${CONFIG_DIR}/manager-server.yaml"

    ["MANAGER_WEB_TEMPLATE_FILE"]="${TEMPLATE_DIR}/manager-web.template.yaml"
    ["MANAGER_WEB_FILE"]="${CONFIG_DIR}/manager-web.yaml"

    ["RUNTIME_TEMPLATE_FILE"]="${TEMPLATE_DIR}/runtime.template.yaml"
    ["RUNTIME_FILE"]="${CONFIG_DIR}/runtime.yaml"

    ["IDENTITY_TEMPLATE_FILE"]="${TEMPLATE_DIR}/identity.template.yaml"
    ["IDENTITY_FILE"]="${CONFIG_DIR}/identity.yaml"

    ["OTEL_TEMPLATE_FILE"]="${TEMPLATE_DIR}/otel.template.yaml"
    ["OTEL_FILE"]="${CONFIG_DIR}/otel.yaml"
    ["LOKI_TEMPLATE_FILE"]="${TEMPLATE_DIR}/loki.template.yaml"
    ["LOKI_FILE"]="${CONFIG_DIR}/loki.yaml"
    ["OBSERVABILITY_TEMPLATE_FILE"]="${TEMPLATE_DIR}/observability.template.yaml"
    ["OBSERVABILITY_FILE"]="${CONFIG_DIR}/observability.yaml"

    ["AS_JSON_TEMPLATE_FILE"]="${TEMPLATE_DIR}/agentserver.template.json"
    ["AS_JSON_FILE"]="${CONFIG_DIR}/agentserver.json"
    ["AS_ENV_TEMPLATE_FILE"]="${TEMPLATE_DIR}/agentserver.template.env"
    ["AS_ENV_FILE"]="${CONFIG_DIR}/agentserver.env"
    ["AS_ENV_YAML_FILE"]="${CONFIG_DIR}/agentserver-env.configmap.yaml"

    ["START_PORT"]="30000"
    ["END_PORT"]="32767"

    ["CLAW_PVC_TEMPLATE_FILE"]="${TEMPLATE_DIR}/claw-pvc.template.yaml"
    ["CLAW_PVC_FILE"]="${CONFIG_DIR}/claw-pvc.yaml"

    ["PV_TEMPLATE_FILE"]="${TEMPLATE_DIR}/pv-nfs.template.yaml"
    ["PV_FILE"]="${CONFIG_DIR}/pv-nfs.yaml"

    ["PVC_TEMPLATE_FILE"]="${TEMPLATE_DIR}/pvc-nfs.template.yaml"
    ["PVC_FILE"]="${CONFIG_DIR}/pvc-nfs.yaml"
)

# Parsed command-line arguments
declare -A ARGS=(
    ["CMD"]=""
)


# ==== All available modules ====
declare -ga ALL_MODULES=("NFS" "NFS-SC" "RABBITMQ" "MYSQL" "POSTGRESQL" "MINIO" "LOG" "JINA" "PROXY" "MONITOR" "GATEWAY" "WEB" "MANAGER" "RUNTIME")

declare -ga MODULES=()

declare -A DEPLOY_VARS=(
    ["AGENT_RUNTIME_IMAGE"]=""
    ["AGENT_RUNTIME_LOG_LEVEL"]="INFO"
    ["AGENT_RUNTIME_NAME"]="jiuwenclaw-agent-runtime"
    ["AGENT_RUNTIME_PORT"]="8091"
    ["AGENT_RUNTIME_REDIS_DB"]="2"
    ["AGENT_RUNTIME_REPLICAS"]="1"
    ["AGENT_RUNTIME_REQUEST_TIMEOUT"]="300"
    ["AGENT_RUNTIME_SCOPE_FULL_TIMEOUT"]="30"
    ["AGENT_RUNTIME_SYNC_TIMEOUT"]="10"
    ["AGENT_RUNTIME_WATCH_INTERVAL"]="10"
    ["AGENT_SERVER_ENV_CM_NAME"]="jiuwenclaw-agentserver-env"
    ["AGENT_SERVER_NAME"]="jiuwenclaw-agentserver"
    ["AGENT_SERVER_PORT"]="8766"
    ["AGENT_SERVER_REACT_MAX_ITER"]="10"
    ["APPLY_PATCH"]="false"
    ["CLAW_FS_GROUP"]="1000"
    ["CLAW_GROUP"]="1000"
    ["CLAW_HOME"]="/home/app"
    ["CLAW_MOUNT_TYPE"]="pvc"
    ["CLAW_POD_CODE_PATH"]="/app/jiuwenswarm"
    ["CLAW_STORAGE_SIZE"]="1Gi"
    ["CLAW_USER"]="1000"
    ["COLLECT_LOG_MASK_ENABLED"]="false"
    ["CORE_POD_PKG_PATH"]="/usr/local/lib/python3.11/site-packages/openjiuwen"
    ["DB_CONNECT_TIMEOUT"]="15"
    ["DB_TYPE"]="mysql"
    ["ENABLE_EXTERNAL_LOKI"]="false"
    ["ENABLE_EXTERNAL_NFS"]="false"
    ["ENABLE_EXTERNAL_OBS"]="false"
    ["ENABLE_EXTERNAL_OTEL"]="false"
    ["ENABLE_EXTERNAL_PVC"]="false"
    ["ENABLE_EXTERNAL_RABBITMQ"]="false"
    ["ENABLE_EXTERNAL_REDIS"]="false"
    ["FLUENT_BIT_IMAGE"]="fluent/fluent-bit:3.0.0"
    ["FLUENT_BIT_NAME"]="fluent-bit"
    ["FUNC_SVC_NAME"]="0@jiuwen@clawtest"
    ["GATEWAY_AGENT_HTTP_MAX_CONNECTIONS"]="200"
    ["GATEWAY_AGENT_HTTP_MAX_KEEPALIVE"]="20"
    ["GATEWAY_CONFIG_HTTP_PORT"]="8775"
    ["GATEWAY_DB_MAX_OVERFLOW"]="20"
    ["GATEWAY_DB_POOL_SIZE"]="2"
    ["GATEWAY_DB_POOL_TIMEOUT"]="30"
    ["GATEWAY_ENV_FILE_CM_NAME"]="jiuwenclaw-gateway-envfile"
    ["GATEWAY_HTTP_PORT"]="19001"
    ["GATEWAY_INSTANCE_ID"]=""
    ["GATEWAY_NAME"]="jiuwenclaw-gateway"
    ["GATEWAY_PORT"]="19001"
    ["GATEWAY_REPLICAS"]="1"
    ["GATEWAY_RUNTIME_MANAGER_URL"]="http://jiuwenclaw-agent-runtime:8091"
    ["GATEWAY_SCHED_LABEL_ENABLED"]="false"
    ["GATEWAY_SESSION_MAP_SCOPE"]="per_chat_bot_user"
    ["GATEWAY_WEB_HTTP_PORT"]="19002"
    ["GATEWAY_WEB_SESSION_STORAGE"]="remote"
    ["GATEWAY_WS_PORT"]="19000"
    ["IDENTITY_ADMIN_PASSWORD"]="admin"
    ["IDENTITY_FEDERATION_CODE_TTL"]="60"
    ["IDENTITY_FEDERATION_DEMO_ADMIN_GROUP"]="enterprise-admins"
    ["IDENTITY_FEDERATION_DEMO_ENABLED"]="false"
    ["IDENTITY_FEDERATION_PUBLIC_PATH_PREFIX"]="/idp"
    ["IDENTITY_FEDERATION_REQUEST_TTL"]="300"
    ["IDENTITY_NAME"]="jiuwenclaw-identity"
    ["IDENTITY_REST_PORT"]="8770"
    ["IDENTITY_SEED_ADMIN"]="true"
    ["IDENTITY_SEED_USER1"]="true"
    ["IDENTITY_USER1_PASSWORD"]="user1"
    ["IS_MOUNT_MANAGER_WEB_CODE"]="false"
    ["IS_MOUNT_OBSERVABILITY_CODE"]="false"
    ["IS_MOUNT_WEB_CODE"]="false"
    ["JINA_CACHE_IMAGE"]="nginx:alpine"
    ["JINA_NAME"]="jina"
    ["JINA_READER_ENDPOINT"]="https://r.jinaai.cn"
    ["JINA_READER_IMAGE"]="ghcr.1ms.run/jina-ai/reader:latest"
    ["JINA_READER_NUM"]="2"
    ["JIUWENBOX_ENABLED"]="true"
    ["JIUWENBOX_IMAGE"]=""
    ["JIUWENBOX_NAME"]="jiuwenbox"
    ["JIUWENBOX_PORT"]="8321"
    ["JIUWENSWARM_CONFIG_DIR"]="/app/config"
    ["JIUWENSWARM_LINK_MTLS_MODE"]="off"
    ["JIUWENSWARM_REQUEST_EXT_FORWARD_HEADERS"]=""
    ["LOGIN_AUTH_SIMULATE"]="false"
    ["LOG_MASK_ENABLED"]="true"
    ["LOG_TO_FILE_ENABLED"]="true"
    ["LOKI_IMAGE"]="grafana/loki:3.0.0"
    ["LOKI_NAME"]="jiuwenclaw-loki"
    ["LOKI_STORAGE_SIZE"]="4Gi"
    ["MANAGER_REST_PORT"]="8765"
    ["MANAGER_SERVER_NAME"]="jiuwenclaw-manager-server"
    ["MANAGER_SERVER_REPLICAS"]="1"
    ["MANAGER_WEB_NAME"]="jiuwenclaw-manager-web"
    ["MANAGER_WEB_PORT"]="5273"
    ["MANAGER_WEB_REPLICAS"]="1"
    ["MANAGER_WEB_RESOLVER"]="auto"
    ["MANAGER_WS_PORT"]="8766"
    ["MINIO_IMAGE"]="minio/minio-arm64:RELEASE.2024-12-18T13-15-44Z"
    ["MINIO_NAME"]="minio"
    ["MINIO_STORAGE_SIZE"]="4Gi"
    ["MODE"]="product"
    ["MYSQL_IMAGE"]="mysql:8.0"
    ["MYSQL_MAX_CONNECTION"]="400"
    ["MYSQL_NAME"]="mysql"
    ["MYSQL_ROOT_PASSWORD"]="Root@123456"
    ["MYSQL_STORAGE_SIZE"]="4Gi"
    ["NAMESPACE"]="default"
    ["NFS_HOST_PATH"]="/data/nfs"
    ["NFS_IMAGE"]="ghcr.io/obeone/nfs-server:2.2.2"
    ["NFS_NAME"]="nfs-server"
    ["NFS_POD_PATH"]="/exports"
    ["NFS_SC_DNAME"]="nfs-provisioner"
    ["NFS_SC_IMAGE"]="registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2"
    ["NFS_SC_NAME"]="nfs-storage"
    ["NFS_SHARE_PATH"]="/"
    ["NO_CHECK_PORTS"]="false"
    ["OBSERVABILITY_IMAGE"]=""
    ["OBSERVABILITY_NAME"]="jiuwenclaw-observability"
    ["OBS_ACCESS_KEY"]="minioadmin"
    ["OBS_BUCKET"]="jiuwenclaw"
    ["OBS_PUBLIC_BASE_URL"]=""
    ["OBS_REGION"]="default"
    ["OBS_SECRET_KEY"]="Minio@123456"
    ["OBS_SECURE"]="false"
    ["OTEL_ENABLED"]="true"
    ["OTEL_IMAGE"]="otel/opentelemetry-collector-contrib:0.104.0"
    ["OTEL_NAME"]="jiuwenclaw-otel-collector"
    ["POOL_ID"]="claw"
    ["POSTGRESQL_IMAGE"]="postgres:16"
    ["POSTGRESQL_MAX_CONNECTION"]="192"
    ["POSTGRESQL_NAME"]="postgresql"
    ["POSTGRESQL_PASSWORD"]="Root@123456"
    ["POSTGRESQL_STORAGE_SIZE"]="4Gi"
    ["PROXY_IMAGE"]="nginx:alpine"
    ["PROXY_NAME"]="proxy"
    ["PROXY_PORT"]="18080"
    ["PROXY_UPSTREAM"]=""
    ["PVC_NAME"]="pvc-nfs-shared"
    ["PV_NAME"]="pv-nfs-shared"
    ["RABBITMQ_IMAGE"]="rabbitmq:3.9.22-management"
    ["RABBITMQ_NAME"]="rabbitmq"
    ["RABBITMQ_PASSWORD"]="Rabbitmq@123"
    ["RABBITMQ_STORAGE_SIZE"]="2Gi"
    ["RABBITMQ_USER"]="admin"
    ["REDIS_DB"]="0"
    ["REDIS_HOST"]=""
    ["REDIS_IMAGE"]="redis:7-alpine"
    ["REDIS_KEY_PREFIX"]="jiuwenclaw:"
    ["REDIS_MODE"]="standalone"
    ["REDIS_NAME"]="jiuwenclaw-redis"
    ["REDIS_PASSWORD"]=""
    ["REDIS_PORT"]="6379"
    ["RENDER_ONLY"]="false"
    ["RUNTIME_POD_CODE_PATH"]="/app/agent-runtime"
    ["RUNTIME_POD_PKG_PATH"]="/usr/local/lib/python3.11/site-packages/openjiuwen_runtime"
    ["SECRET_CM_NAME"]="jiuwenclaw-secret-configmap"
    ["TIMEZONE"]="Asia/Shanghai"
    ["TOOL_RESULT_DISPLAY_MAX_CHARS"]="500"
    ["USER_WEB_IDP_TARGET"]=""
    ["USER_WEB_MANAGER_TARGET"]=""
    ["VAR_LIB_DOCKER_PATH"]="/var/lib/containerd"
    ["VECTOR_IMAGE"]="timberio/vector:0.40.0-alpine"
    ["VECTOR_NAME"]="vector-receiver"
    ["WEB_HTTP_PORT"]="5173"
    ["WEB_NAME"]="jiuwenclaw-web"
    ["WEB_PORT"]="19000"
    ["WEB_REPLICAS"]="1"
    ["WEB_WS_PORT"]="19000"
)

declare -A OYR_COMPONENTS=(
        ["frontend"]="deployment"
        ["function-scheduler"]="deployment"
        ["function-manager"]="deployment"
        ["function-master"]="deployment"
        ["meta-service"]="deployment"
        ["iam-adaptor"]="deployment"
        ["function-proxy"]="daemonset"
        ["ds-worker"]="daemonset"
        ["etcd"]="statefulset"
        ["minio"]="statefulset"
    )
